### ISSUE TITLE
Searching for maintainers!

### ISSUE THREAD

**Issue by keen99** [keen99/puppet-beanstalkd#7]
Actively looking for a new maintainer - if someone would like to take this over, or simply be given write access, lets talk.   I hate abandonware, but I don't have any time to spend with this.

@Jmeyering @Richtermeister @jtreminio @rentrak @alehkot

**Comment by jtreminio** [comment]
I wouldn't mind taking over. My fork at https://github.com/puphpet/puppet-beanstalkd/commits/master already has some fixes yours doesn't.

Either way, thanks for the work you've done up until now.

**Comment by Richtermeister** [comment]
:+1:  for @jtreminio ! While on subject, I believe there's a fix in this package which isn't in your fork: https://github.com/keen99/puppet-beanstalkd/pull/5

At least last time I tried I wasn't able to specify listen/port from puppet config with the standard puphet setup. Thx!

**Comment by jtreminio** [comment]
@Richtermeister 
![image](https://cloud.githubusercontent.com/assets/589398/6785709/5250e236-d155-11e4-9e56-8819d96ba674.png)

I believe most issues were fixed by puphpet/puppet-beanstalkd/commit/5a530ffec1f3fd79a1c0bdc8ba2201c33d86f4ab

**Comment by Richtermeister** [comment]
Oh sweet, looks that way. I will give that another shot. Keep up the great work, big fan of puphpet!

**Comment by keen99** [comment]
@jtreminio  added as collaborator - let me know if that does the trick - GHE collaborator perms are definitely different than GH. :)
